name: http_interop
description: A thin abstraction layer for interoperability between HTTP client/server implementations.
version: 1.0.0
repository: https://github.com/f3ath/dart-http-interop

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^2.0.1
  cider: ^0.2.3
  test: ^1.21.1
  check_coverage: ^0.0.2

cider:
  link_template:
    tag: 'https://github.com/f3ath/dart-http-interop/releases/tag/%tag%'
    diff: 'https://github.com/f3ath/dart-http-interop/compare/%from%...%to%'
