name: http_interop
description: A thin abstraction layer for interoperability between HTTP client/server implementations.
version: 2.1.1
repository: https://github.com/f3ath/dart-http-interop

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^5.0.0
  cider: ^0.2.8
  test: ^1.25.8
  check_coverage: ^0.0.7

cider:
  link_template:
    tag: 'https://github.com/f3ath/dart-http-interop/releases/tag/%tag%'
    diff: 'https://github.com/f3ath/dart-http-interop/compare/%from%...%to%'
