name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  dart:stable
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Downgrade
        run: dart pub downgrade
      - name: Analyzer
        run: dart analyze --fatal-infos --fatal-warnings
